[
  # emojis
  { out = "💣"; seq = "bomb";        }
  { out = "💥"; seq = "boom";        }
  { out = "💡"; seq = "bulb";        }
  { out = "💩"; seq = "poop";        }
  { out = "🐡"; seq = "puffy";       }
  { out = "🎉"; seq = "tada";        }
  { out = "💤"; seq = "zzz";         }
  { out = "⚓"; seq = "anchor";      }
  { out = "⛵"; seq = "boat";        }
  { out = "🐙"; seq = "octo";        }
  { out = "💡"; seq = "octopus";     }
  { out = "😎"; seq = "sunglass";    }
  { out = "😎"; seq = "sunglasses";  }
  { out = "👍"; seq = "+1";          }
  { out = "👍"; seq = "yes";         }
  { out = "👎"; seq = "no";          }
  { out = "👌"; seq = "pft";         }
  { out = "👌"; seq = "perfect";     }
  { out = "👌"; seq = "pft";         }
  { out = "🤌"; seq = "mammamia";    }
  { out = "🤌"; seq = "mamamia";     }
  { out = "🤌"; seq = "coxinha";     }
  { out = "🍿"; seq = "popcorn";     }
  { out = "👆"; seq = "pointup";     }
  { out = "👇"; seq = "pointdown";   }
  { out = "🆙"; seq = "up";          }
  { out = "🖕"; seq = "fucku";       }
  { out = "🫶"; seq = "s2";          }
  { out = "🙏"; seq = "pray";        }
  { out = "🤝"; seq = "agree";       }
  { out = "👏"; seq = "claps";       }
  { out = "💪"; seq = "muscle";      }
  { out = "👀"; seq = "eyes";        }
  { out = "🥂"; seq = "cheers";      }
  { out = "❤"; seq = "heart";        }
  { out = "🙊"; seq = "notsay";      }
  { out = "🙉"; seq = "nothear";     }
  { out = "🙈"; seq = "notsee";      }
  { out = "😩"; seq = "lazy";        }
  { out = "😫"; seq = "fresco";      }
  { out = "😫"; seq = "fussy";       }
  { out = "🥱"; seq = "bocejo";      }
  { out = "🥱"; seq = "sono";        }
  { out = "😓"; seq = "'-.-";        }
  { out = "😓"; seq = "-.-'";        }
  { out = "😱"; seq = "lol";         }
  { out = "😭"; seq = "cry";         }
  { out = "😭"; seq = ";-;";         }
  { out = "😭"; seq = "T-T";         }
  { out = "😰"; seq = "'o-o";        }
  { out = "😰"; seq = "o-o'";        }
  { out = "😳"; seq = "shy";         }
  { out = "😮"; seq = ":o";          }
  { out = "🧐"; seq = "o.O";         }
  { out = "🥸"; seq = "who?";        }
  { out = "🥵"; seq = "hot";         }
  { out = "🤮"; seq = "ew";          }
  { out = "🤮"; seq = "vomit";       }
  { out = "😔"; seq = "u-u";         }
  { out = "🤤"; seq = "baba";        }
  { out = "🤤"; seq = "babando";     }
  { out = "🫩"; seq = "bored";       }
  { out = "😬"; seq = "hm";          }
  { out = "🤔"; seq = "think";       }
  { out = "🤔"; seq = "thinking";    }
  { out = "🤪"; seq = "crazy";       }
  { out = "🙂"; seq = "smile";       }
  { out = "🙂"; seq = "c:";          }
  { out = "🫠"; seq = "melting";     }
  { out = "🫠"; seq = "derretendo";  }
  { out = "😀"; seq = ":)";          }
  { out = "😄"; seq = ":D";          }
  { out = "🤣"; seq = "xD";          }
  { out = "🤣"; seq = "XD";          }
  { out = "😂"; seq = "laught";      }
  { out = "😂"; seq = "funny";       }
  { out = "😂"; seq = "rindo";       }
  { out = "😇"; seq = "angel";       }
  { out = "😇"; seq = "inocent";     }
  { out = "😍"; seq = "inlove";      }
  { out = "😍"; seq = "love";        }
  { out = "😍"; seq = "hearteyes";   }
  { out = "😋"; seq = ":P";          }
  { out = "😵"; seq = "x.x";         }
  { out = "😵‍💫"; seq = "spiral";      }
  { out = "😵‍💫"; seq = "tonto";       }
  { out = "🤯"; seq = "wow";         }
  { out = "🥺"; seq = "pleading";    }
  { out = "😡"; seq = "angry";       }
  { out = "🤬"; seq = "rage";        }
  { out = "💀"; seq = "skull";       }
  { out = "💀"; seq = "dead";        }
  { out = "👽"; seq = "alien";       }
  { out = "🤖"; seq = "robot";       }
  { out = "🤡"; seq = "clown";       }
  { out = "👮"; seq = "police";      }
  { out = "🇧🇷"; seq = "br";          }
  { out = "🚓"; seq = "policecar";   }
  { out = "🚀"; seq = "rocket";      }
  { out = "✅"; seq = "check";       }
  { out = "❌"; seq = "error";       }
  { out = "❌"; seq = "false";       }
  { out = "❓"; seq = "?";           }
  { out = "❗"; seq = "!";           }
  { out = "🆗"; seq = "ok";          }
  { out = "🍆"; seq = "eggplant";    }
  { out = "🍆"; seq = "berinjela";   }
  { out = "🍌"; seq = "banana";      }
  { out = "🍕"; seq = "pizza";       }
  { out = "🍪"; seq = "cookie";      }
  { out = "🏆"; seq = "trophy";      }
  { out = "🏆"; seq = "trofeu";      }
  { out = "🐍"; seq = "snake";       }
  { out = "🔥"; seq = "fire";        }
  { out = "🤓"; seq = "nerd";        }

  { out = "😅"; seq = "suor";        }
  { out ="😗🎶";seq = "inno";        }
  { out ="🥁";seq = "tambor";        }

  #needed
  # { out = "\\" ;seq = "";             }
  #math

]
